const Products = [{
    "id": 1,
    "ProductName": "Pearson",
    "description": "Silvester",
    "price": "$918.72"
  }, {
    "id": 2,
    "ProductName": "Autumn Leaf",
    "description": "Regardsoe",
    "price": "$617.72"
  }, {
    "id": 3,
    "ProductName": "3rd",
    "description": "Dradey",
    "price": "$646.85"
  }, {
    "id": 4,
    "ProductName": "Elmside",
    "description": "Parlett",
    "price": "$201.64"
  }, {
    "id": 5,
    "ProductName": "Golden Leaf",
    "description": "Truelove",
    "price": "$162.40"
  }, {
    "id": 6,
    "ProductName": "Vernon",
    "description": "Stennett",
    "price": "$839.23"
  }, {
    "id": 7,
    "ProductName": "Elmside",
    "description": "Lanfear",
    "price": "$818.86"
  }, {
    "id": 8,
    "ProductName": "Larry",
    "description": "Bruckshaw",
    "price": "$231.84"
  }, {
    "id": 9,
    "ProductName": "Park Meadow",
    "description": "Izsak",
    "price": "$233.61"
  }, {
    "id": 10,
    "ProductName": "Scott",
    "description": "Matveiko",
    "price": "$71.48"
  }, {
    "id": 11,
    "ProductName": "Hooker",
    "description": "Ellsbury",
    "price": "$420.16"
  }, {
    "id": 12,
    "ProductName": "Southridge",
    "description": "Trotter",
    "price": "$449.73"
  }, {
    "id": 13,
    "ProductName": "Heffernan",
    "description": "Capaldo",
    "price": "$208.76"
  }, {
    "id": 14,
    "ProductName": "Autumn Leaf",
    "description": "Armin",
    "price": "$977.93"
  }, {
    "id": 15,
    "ProductName": "Jenifer",
    "description": "Maslin",
    "price": "$922.56"
  }, {
    "id": 16,
    "ProductName": "Heath",
    "description": "Quin",
    "price": "$935.13"
  }, {
    "id": 17,
    "ProductName": "Swallow",
    "description": "March",
    "price": "$480.29"
  }, {
    "id": 18,
    "ProductName": "Lawn",
    "description": "Sheards",
    "price": "$514.71"
  }, {
    "id": 19,
    "ProductName": "Sundown",
    "description": "Tench",
    "price": "$399.43"
  }, {
    "id": 20,
    "ProductName": "Northfield",
    "description": "Roscamp",
    "price": "$679.27"
  }]
  

export default Products;